---
title: "Orderly Tutorial"
author: "MRC Centre for Global Infectious Disease Analysis"
---

```{r}
#| include: false
#| cache: false
source("support.R")
```

## The reproducibility rant

[Slide Deck](https://docs.google.com/presentation/d/1Hj82bIQOLx78lOcPP_SwCMsw3nakwvubjlbCAS6OR_A/present?usp=sharing){preview-link="false"}

## Who uses it?

- Developed since May 2017 for the [Vaccine Impact Modelling Consortium](https://www.vaccineimpact.org/)
- Adopted by the MRC Centre and used in the 2018-2020 DRC Ebola responses
- Used in the COVID-19 response, especially within the "real time modelling" group
- Used within research groups (HIV, Malaria, possibly others?)

## Historical notes {.smaller}

* [`orderly`](https://vimc.github.io/orderly) (version 1)
  - Created for [Vaccine Impact Modelling Consortium](https://www.vaccineimpact.org/) and strongly focussed on **reproducible research**
  - Used [YAML](https://en.wikipedia.org/wiki/YAML) everywhere
  - Supported simple ways of working for a small centralised team
* [`orderly2`](https://mrc-ide.github.io/orderly2) (soon to be `orderly` 2.0.0)
  - A complete rewrite taking the best ideas from version 1 and dropping many less useful bits
  - Easier to program against
  - No more YAML
  - Focusses on **distributed collaborative analysis**
  - Also available as a [python package](https://pypi.org/project/pyorderly/)!

## Situation report

* Open RStudio - is it installed?
* Check your R version - does it start with 4.4?
* Do you have git installed?
* Does your RStudio have a git button?
* Go to <https://github.com> - are you logged in?
* Go to <https://github.com/settings/organizations> - are you in `mrc-ide`?

## Next steps

* On to [getting started](getting-started.html)
* Back to the [project root](..)
